package calculator;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.EtchedBorder;
import javax.swing.border.LineBorder;
/**
 * Created with Netbeans using GUI builder
 * @author Fausto JC Boko
 */
public class CalculatorGui extends javax.swing.JFrame {
    private static final EtchedBorder CHANGE_PRESSED_BORDER = new EtchedBorder(1, Color.GRAY, Color.GRAY);
    private static final LineBorder CHANGE_RELEASE_BORDER = new LineBorder(Color.LIGHT_GRAY, 1);
    
    /**
     * Creates new form CalculatorGui
     */
    public CalculatorGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        jLabelAnswer = new javax.swing.JLabel();
        jLabelPlus = new javax.swing.JLabel();
        jLabelMinus = new javax.swing.JLabel();
        jLabelMultiply = new javax.swing.JLabel();
        jLabelDivide = new javax.swing.JLabel();
        jLabelTan = new javax.swing.JLabel();
        jLabelCos = new javax.swing.JLabel();
        jLabelSin = new javax.swing.JLabel();
        jLabelBackspace = new javax.swing.JLabel();
        jLabelClear = new javax.swing.JLabel();
        jLabelPower = new javax.swing.JLabel();
        jLabelSquareRoot = new javax.swing.JLabel();
        jLabelOpenParenthesis = new javax.swing.JLabel();
        jLabelCloseParenthesis = new javax.swing.JLabel();
        jTextFieldExpression = new javax.swing.JTextField();
        jTextFieldAnswerBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHistory = new javax.swing.JTextArea();
        jLabelDot = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setEnabled(false);
        jPanel1.setFocusable(false);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(formListener);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(formListener);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(formListener);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(formListener);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(formListener);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(formListener);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(formListener);

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(formListener);

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(formListener);

        jLabel0.setBackground(new java.awt.Color(51, 51, 51));
        jLabel0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel0.setForeground(new java.awt.Color(204, 204, 204));
        jLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0.setText("0");
        jLabel0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel0.setName("0"); // NOI18N
        jLabel0.addMouseListener(formListener);

        jLabelAnswer.setBackground(new java.awt.Color(0, 204, 102));
        jLabelAnswer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAnswer.setForeground(new java.awt.Color(51, 51, 51));
        jLabelAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnswer.setText("=");
        jLabelAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelAnswer.setOpaque(true);
        jLabelAnswer.addMouseListener(formListener);

        jLabelPlus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPlus.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPlus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlus.setText("+");
        jLabelPlus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelPlus.addMouseListener(formListener);

        jLabelMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMinus.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMinus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinus.setText("-");
        jLabelMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelMinus.addMouseListener(formListener);

        jLabelMultiply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMultiply.setForeground(new java.awt.Color(204, 204, 204));
        jLabelMultiply.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMultiply.setText("*");
        jLabelMultiply.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelMultiply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMultiply.addMouseListener(formListener);

        jLabelDivide.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDivide.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDivide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDivide.setText("/");
        jLabelDivide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelDivide.addMouseListener(formListener);

        jLabelTan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTan.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTan.setText("tan");
        jLabelTan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelTan.addMouseListener(formListener);

        jLabelCos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCos.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCos.setText("cos");
        jLabelCos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelCos.addMouseListener(formListener);

        jLabelSin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSin.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSin.setText("sin");
        jLabelSin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelSin.addMouseListener(formListener);

        jLabelBackspace.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBackspace.setForeground(new java.awt.Color(204, 204, 204));
        jLabelBackspace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBackspace.setText("<--");
        jLabelBackspace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelBackspace.addMouseListener(formListener);

        jLabelClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelClear.setForeground(new java.awt.Color(204, 204, 204));
        jLabelClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClear.setText("CLS");
        jLabelClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelClear.addMouseListener(formListener);

        jLabelPower.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPower.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPower.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPower.setText("^");
        jLabelPower.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelPower.addMouseListener(formListener);

        jLabelSquareRoot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSquareRoot.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSquareRoot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSquareRoot.setText("sqrt");
        jLabelSquareRoot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelSquareRoot.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabelSquareRoot.setDoubleBuffered(true);
        jLabelSquareRoot.addMouseListener(formListener);

        jLabelOpenParenthesis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelOpenParenthesis.setForeground(new java.awt.Color(204, 204, 204));
        jLabelOpenParenthesis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOpenParenthesis.setText("(");
        jLabelOpenParenthesis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelOpenParenthesis.addMouseListener(formListener);

        jLabelCloseParenthesis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCloseParenthesis.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCloseParenthesis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseParenthesis.setText(")");
        jLabelCloseParenthesis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelCloseParenthesis.addMouseListener(formListener);

        jTextFieldExpression.setEditable(false);
        jTextFieldExpression.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldExpression.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldExpression.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldExpression.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldExpression.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextFieldExpression.setScrollOffset(1);

        jTextFieldAnswerBox.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldAnswerBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldAnswerBox.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldAnswerBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAnswerBox.setBorder(null);

        jTextAreaHistory.setBackground(new java.awt.Color(51, 51, 51));
        jTextAreaHistory.setColumns(20);
        jTextAreaHistory.setForeground(new java.awt.Color(204, 204, 204));
        jTextAreaHistory.setRows(5);
        jTextAreaHistory.setWrapStyleWord(true);
        jTextAreaHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextAreaHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextAreaHistory.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextAreaHistory);
        jTextAreaHistory.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabelDot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDot.setForeground(new java.awt.Color(204, 204, 204));
        jLabelDot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDot.setText(".");
        jLabelDot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabelDot.addMouseListener(formListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelClear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOpenParenthesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelSin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelCos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCloseParenthesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelTan, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabelDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabelDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                .addComponent(jLabelPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelAnswer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldAnswerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAnswerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTan))
                    .addComponent(jLabelSin))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBackspace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCloseParenthesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOpenParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabelSquareRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.MouseListener {
        FormListener() {}
        
        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jLabel1) {
                CalculatorGui.this.jLabel1MousePressed(evt);
            }
            else if (evt.getSource() == jLabel2) {
                CalculatorGui.this.jLabel2MousePressed(evt);
            }
            else if (evt.getSource() == jLabel3) {
                CalculatorGui.this.jLabel3MousePressed(evt);
            }
            else if (evt.getSource() == jLabel4) {
                CalculatorGui.this.jLabel4MousePressed(evt);
            }
            else if (evt.getSource() == jLabel5) {
                CalculatorGui.this.jLabel5MousePressed(evt);
            }
            else if (evt.getSource() == jLabel6) {
                CalculatorGui.this.jLabel6MousePressed(evt);
            }
            else if (evt.getSource() == jLabel7) {
                CalculatorGui.this.jLabel7MousePressed(evt);
            }
            else if (evt.getSource() == jLabel8) {
                CalculatorGui.this.jLabel8MousePressed(evt);
            }
            else if (evt.getSource() == jLabel9) {
                CalculatorGui.this.jLabel9MousePressed(evt);
            }
            else if (evt.getSource() == jLabel0) {
                CalculatorGui.this.jLabel0MousePressed(evt);
            }
            else if (evt.getSource() == jLabelAnswer) {
                CalculatorGui.this.jLabelAnswerMousePressed(evt);
            }
            else if (evt.getSource() == jLabelPlus) {
                CalculatorGui.this.jLabelPlusMousePressed(evt);
            }
            else if (evt.getSource() == jLabelMinus) {
                CalculatorGui.this.jLabelMinusMousePressed(evt);
            }
            else if (evt.getSource() == jLabelMultiply) {
                CalculatorGui.this.jLabelMultiplyMousePressed(evt);
            }
            else if (evt.getSource() == jLabelDivide) {
                CalculatorGui.this.jLabelDivideMousePressed(evt);
            }
            else if (evt.getSource() == jLabelTan) {
                CalculatorGui.this.jLabelTanMousePressed(evt);
            }
            else if (evt.getSource() == jLabelCos) {
                CalculatorGui.this.jLabelCosMousePressed(evt);
            }
            else if (evt.getSource() == jLabelSin) {
                CalculatorGui.this.jLabelSinMousePressed(evt);
            }
            else if (evt.getSource() == jLabelBackspace) {
                CalculatorGui.this.jLabelBackspaceMousePressed(evt);
            }
            else if (evt.getSource() == jLabelClear) {
                CalculatorGui.this.jLabelClearMousePressed(evt);
            }
            else if (evt.getSource() == jLabelPower) {
                CalculatorGui.this.jLabelPowerMousePressed(evt);
            }
            else if (evt.getSource() == jLabelSquareRoot) {
                CalculatorGui.this.jLabelSquareRootMousePressed(evt);
            }
            else if (evt.getSource() == jLabelOpenParenthesis) {
                CalculatorGui.this.jLabelOpenParenthesisMousePressed(evt);
            }
            else if (evt.getSource() == jLabelCloseParenthesis) {
                CalculatorGui.this.jLabelCloseParenthesisMousePressed(evt);
            }
            else if (evt.getSource() == jLabelDot) {
                CalculatorGui.this.jLabelDotMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jLabel1) {
                CalculatorGui.this.jLabel1MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel2) {
                CalculatorGui.this.jLabel2MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel3) {
                CalculatorGui.this.jLabel3MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel4) {
                CalculatorGui.this.jLabel4MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel5) {
                CalculatorGui.this.jLabel5MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel6) {
                CalculatorGui.this.jLabel6MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel7) {
                CalculatorGui.this.jLabel7MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel8) {
                CalculatorGui.this.jLabel8MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel9) {
                CalculatorGui.this.jLabel9MouseReleased(evt);
            }
            else if (evt.getSource() == jLabel0) {
                CalculatorGui.this.jLabel0MouseReleased(evt);
            }
            else if (evt.getSource() == jLabelAnswer) {
                CalculatorGui.this.jLabelAnswerMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelPlus) {
                CalculatorGui.this.jLabelPlusMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelMinus) {
                CalculatorGui.this.jLabelMinusMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelMultiply) {
                CalculatorGui.this.jLabelMultiplyMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelDivide) {
                CalculatorGui.this.jLabelDivideMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelTan) {
                CalculatorGui.this.jLabelTanMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelCos) {
                CalculatorGui.this.jLabelCosMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelSin) {
                CalculatorGui.this.jLabelSinMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelBackspace) {
                CalculatorGui.this.jLabelBackspaceMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelClear) {
                CalculatorGui.this.jLabelClearMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelPower) {
                CalculatorGui.this.jLabelPowerMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelOpenParenthesis) {
                CalculatorGui.this.jLabelOpenParenthesisMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelCloseParenthesis) {
                CalculatorGui.this.jLabelCloseParenthesisMouseReleased(evt);
            }
            else if (evt.getSource() == jLabelDot) {
                CalculatorGui.this.jLabelDotMouseReleased(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Mouse PRESSED Event">
    private void jLabelAnswerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnswerMousePressed
        jLabelAnswer.setBorder(CHANGE_PRESSED_BORDER);
        try {
            ExpressionCalculate ec = new ExpressionCalculate();
            String answer = ec.getResult(jTextFieldExpression.getText());

            if (!jTextFieldExpression.getText().isEmpty()) {
               jTextFieldAnswerBox.setText(answer);
               jTextAreaHistory.append(" " + jTextFieldExpression.getText() + " = " + answer + "\n");
               jTextFieldExpression.setText("");
            }
        } catch (Exception ex) {
            if (jTextFieldExpression.getText().isEmpty()) jTextFieldAnswerBox.setText("NO EXPRESSION");
            else jTextFieldAnswerBox.setText("Syntax Error");
            Logger.getLogger(Main.class.getName()).log(Level.WARNING, null, ex);
        }
    }//GEN-LAST:event_jLabelAnswerMousePressed

    private void jLabel0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MousePressed
       jTextFieldExpression.setText(jTextFieldExpression.getText() + "0");
       jLabel0.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel0MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "1");
        jLabel1.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "2");
        jLabel2.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "3");
        jLabel3.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "4");
        jLabel4.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "5");
        jLabel5.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        jLabel6.setBorder(CHANGE_RELEASE_BORDER);     
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "7");
        jLabel7.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "8");
        jLabel8.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "9");
        jLabel9.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabelPlusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlusMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "+");
        jLabelPlus.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelPlusMousePressed

    private void jLabelMinusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinusMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "-");
        jLabelMinus.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelMinusMousePressed

    private void jLabelMultiplyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMultiplyMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "*");
        jLabelMultiply.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelMultiplyMousePressed

    private void jLabelDivideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDivideMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "/");
        jLabelDivide.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelDivideMousePressed

    private void jLabelOpenParenthesisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpenParenthesisMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "(");
        jLabelOpenParenthesis.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelOpenParenthesisMousePressed

    private void jLabelCloseParenthesisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseParenthesisMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + ")");
        jLabelCloseParenthesis.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelCloseParenthesisMousePressed

    private void jLabelClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMousePressed
        jTextFieldExpression.setText("");
        jLabelClear.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelClearMousePressed

    private void jLabelSinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSinMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "sin(");
        jLabelSin.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelSinMousePressed

    private void jLabelCosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCosMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "cos(");
        jLabelCos.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelCosMousePressed

    private void jLabelTanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTanMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "tan(");
        jLabelTan.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelTanMousePressed

    private void jLabelPowerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPowerMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "^");
        jLabelPower.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelPowerMousePressed

    private void jLabelDotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDotMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + ".");
        jLabelDot.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelDotMousePressed
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Mouse RELEASE Event">
    private void jLabel0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MouseReleased
        jLabel0.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel0MouseReleased

    private void jLabelBackspaceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackspaceMousePressed
        if (!jTextFieldExpression.getText().isEmpty()) jTextFieldExpression.setText(jTextFieldExpression.getText().substring(0, jTextFieldExpression.getText().length()-1));
        jLabelBackspace.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelBackspaceMousePressed

    private void jLabelBackspaceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackspaceMouseReleased
        jLabelBackspace.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelBackspaceMouseReleased

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        jLabel1.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        jLabel2.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        jLabel3.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        jLabel4.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        jLabel5.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "6");
        jLabel6.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        jLabel7.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        jLabel8.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        jLabel9.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabelAnswerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnswerMouseReleased
        jLabelAnswer.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelAnswerMouseReleased

    private void jLabelClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMouseReleased
        jLabelClear.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelClearMouseReleased

    private void jLabelOpenParenthesisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpenParenthesisMouseReleased
        jLabelOpenParenthesis.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelOpenParenthesisMouseReleased

    private void jLabelCloseParenthesisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseParenthesisMouseReleased
        jLabelCloseParenthesis.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelCloseParenthesisMouseReleased

    private void jLabelSinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSinMouseReleased
        jLabelSin.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelSinMouseReleased

    private void jLabelCosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCosMouseReleased
        jLabelCos.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelCosMouseReleased

    private void jLabelTanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTanMouseReleased
        jLabelTan.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelTanMouseReleased

    private void jLabelPlusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlusMouseReleased
        jLabelPlus.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelPlusMouseReleased

    private void jLabelMinusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinusMouseReleased
        jLabelMinus.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelMinusMouseReleased

    private void jLabelMultiplyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMultiplyMouseReleased
        jLabelMultiply.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelMultiplyMouseReleased

    private void jLabelDivideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDivideMouseReleased
        jLabelDivide.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelDivideMouseReleased

    private void jLabelDotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDotMouseReleased
        jLabelDot.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelDotMouseReleased

    private void jLabelSquareRootMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSquareRootMousePressed
        jTextFieldExpression.setText(jTextFieldExpression.getText() + "sqrt(");
        jLabelSquareRoot.setBorder(CHANGE_PRESSED_BORDER);
    }//GEN-LAST:event_jLabelSquareRootMousePressed

    private void jLabelPowerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPowerMouseReleased
        jLabelPower.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelPowerMouseReleased
    
    private void jLabelSquareRootMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSquareRootMouseReleased
        jLabelSquareRoot.setBorder(CHANGE_RELEASE_BORDER);
    }//GEN-LAST:event_jLabelSquareRootMouseReleased
    
    //</editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel0;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelAnswer;
    public javax.swing.JLabel jLabelBackspace;
    public javax.swing.JLabel jLabelClear;
    public javax.swing.JLabel jLabelCloseParenthesis;
    public javax.swing.JLabel jLabelCos;
    public javax.swing.JLabel jLabelDivide;
    public javax.swing.JLabel jLabelDot;
    public javax.swing.JLabel jLabelMinus;
    public javax.swing.JLabel jLabelMultiply;
    public javax.swing.JLabel jLabelOpenParenthesis;
    public javax.swing.JLabel jLabelPlus;
    public javax.swing.JLabel jLabelPower;
    public javax.swing.JLabel jLabelSin;
    public javax.swing.JLabel jLabelSquareRoot;
    public javax.swing.JLabel jLabelTan;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextAreaHistory;
    public javax.swing.JTextField jTextFieldAnswerBox;
    public javax.swing.JTextField jTextFieldExpression;
    // End of variables declaration//GEN-END:variables
}
